openapi: 3.0.1
info:
  title: contact-service API
  version: 1.0.0
  description: |
    Contact Service
servers:
  - url: http://localhost:8074
    description: Generated server url
tags:
  - name: contact-service
    description: contact-service
  - name: Beneficiary Account
    description: Beneficiary Account
paths:
  /contacts:
    get:
      tags:
        - contact
      summary: Get the list of contact by user identity
      operationId: getContactList
      parameters:
        - name : userId
          in : query
          description: user id
          required: false
          schema:
            type: string
          example: 123
        - name : searchText
          in : query
          description: search text
          required: false
          schema:
            type: string
          example: abc
      responses:
        503:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        200:
          description: Retrieve data succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryResponse'
        404:
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
        400:
          description: Input data is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      security:
        - Bearer: [ ]
    post:
      tags:
        - contact
      summary: Create a new contact for given user identity
      operationId: createContact
      requestBody:
        description: Contact data model
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeneficiaryRecord'
      responses:
          503:
            description: Internal server error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
          201:
            description: Contact data model created succesfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/BeneficiaryCreateResponse'
          404:
            description: Data Not Found
            content:
              application/json:
                schema:
                  type: string
          400:
            description: Input data is invalid
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
          401:
            description: Unauthorized
            content:
              application/json:
                schema:
                  type: string
      security:
        - Bearer: [ ]
  /beneficiaries/-/mobile-numbers/{mobileNumber}:
    get:
      tags:
        -  Beneficiary Account
      summary: Lookup beneficiary account by mobile number
      description: Lookup beneficiary account by mobile number
      operationId:  lookupBeneficiaryAccountWithMobile
      parameters:
        - name: mobileNumber
          in: path
          description: Mobile Number
          required: true
          schema:
            type: string
          example: 65086508427
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryAccountResponse'
        503:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
        400:
          description: Input data is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      security:
        - Bearer: [ ]
  /beneficiaries/-/account-numbers/{accountNumber}:
    get:
      tags:
        - Beneficiary Account
      summary: Lookup beneficiary account by account number
      description: Lookup beneficiary account by account number
      operationId:  lookupBeneficiaryAccount
      parameters:
        - name: accountNumber
          in: path
          description: Account Number
          required: true
          schema:
            type: string
          example: 120086508427
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryAccountResponse'
        503:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
        400:
          description: Input data is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      security:
        - Bearer: [ ]
  /beneficiaries:
    get:
      tags:
        - Beneficiary Account
      summary: Lookup beneficiary account
      description: Lookup beneficiary account
      operationId:  lookupBeneficiary
      parameters:
        - name: mobileNumber
          in: path
          description: Mobile Number
          required: false
          schema:
            type: string
          example: 65086508427
        - name: accountNumber
          in: query
          description: Account Number
          required: false
          schema:
            type: string
          example: 120086508427
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeneficiaryAccountResponse'
        503:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
        400:
          description: Input data is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      security:
        - Bearer: [ ]
#-----
components:
  schemas:
    BeneficiaryCreateResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/BeneficiaryRecord'
    BeneficiaryResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/BeneficiaryRecord'
        pagging:
          $ref: '#/components/schemas/PagingInformation'
        status:
          $ref: '#/components/schemas/ResponseStatus'
    ServiceDataResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
        pagging:
          $ref: '#/components/schemas/PagingInformation'
        status:
          $ref: '#/components/schemas/ResponseStatus'
    PagingInformation:
      type: object
      properties:
        totalRecords:
          type: number
        pageSize:
          type: integer
        pageNumber:
          type: integer
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ResponseStatus'
    ResponseStatus:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    BeneficiaryAccountResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/BeneficiaryAccount'
    BeneficiaryAccount:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
          readOnly: true
        accountNumber:
          type: string
          readOnly: true
        displayName:
          type: string
    BeneficiaryRecord:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        serviceCode:
          type: string
        subServiceCode:
          type: string
        displayName:
          type: string
        paymentReference:
          type: string
        mobileNumber:
          type: string
        accountNumber:
          type: string
        branchCode:
          type: string
        bankCode:
          type: string
        city:
          type: string
        state:
          type: string
        postCode:
          type: string
        address:
          type: string
        verificationStatus:
          type: string
        verificationAt:
          type: string
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer