openapi: 3.0.1
info:
  title: service_name-service API
  version: 1.0.0
  description: |
    Service description here.
    Please add more...
servers:
  - url: http://localhost:8074
    description: Generated server url
tags:
  - name: service_name-service
    description: service_name-service
paths:
  /sample-data:
    get:
      tags:
        - service_name-service
      summary: Retrive example data
      operationId: getExampleData
      responses:
        503:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        200:
          description: Retrieve data succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceDataResponse'
        404:
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
        400:
          description: Input data is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      security:
        - Bearer: []
#-----
components:
  schemas:
    ServiceDataResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
        pagging:
          $ref: '#/components/schemas/PagingInformation'
        status:
          $ref: '#/components/schemas/ResponseStatus'
    PagingInformation:
      type: object
      properties:
        totalRecords:
          type: number
        pageSize:
          type: integer
        pageNumber:
          type: integer
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ResponseStatus'
    ResponseStatus:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer